#! /bin/sh
<<VIM
// vim: set ft=sh:
VIM
# totally just a script version of https://mastodon.social/@climagic/104478724407900816
# all props to the imagemagick devs, really.

Help() {

cat <<END_OF_HELP

$(basename "$0")
  Add top and bottom text to a file
  Requirements: imagemagick, impact font

  -h - Show this help
  -t - Top Text
  -b - Bottom text
  -i - Input image
  -o - Output image

END_OF_HELP
  exit 0
}

while getopts 'ht:b:i:o:' OPT;
do
  case $OPT in
    h) Help ;;
    i) INIMG=$OPTARG ;;
    o) OUTIMG=$OPTARG ;;
    t) TOPTEXT=$OPTARG ;;
    b) BOTTEXT=$OPTARG ;;
  esac
done


convert $INIMG \
  -font impact -fill white -pointsize 84 -stroke black -strokewidth 3 -gravity north \
  -resize '1080' \
  -annotate +0+20 "$TOPTEXT" -gravity south \
  -annotate +0+20 "$BOTTEXT" \
  $OUTIMG # Make your own meme image using Imagemagick.


  # This is free and unencumbered software released into the public domain.
  #
  # Anyone is free to copy, modify, publish, use, compile, sell, or
  # distribute this software, either in source code form or as a compiled
  # binary, for any purpose, commercial or non-commercial, and by any
  # means.
  #
  # In jurisdictions that recognize copyright laws, the author or authors
  # of this software dedicate any and all copyright interest in the
  # software to the public domain. We make this dedication for the benefit
  # of the public at large and to the detriment of our heirs and
  # successors. We intend this dedication to be an overt act of
  # relinquishment in perpetuity of all present and future rights to this
  # software under copyright law.
  #
  # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  # EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
  # IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
  # OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
  # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
  # OTHER DEALINGS IN THE SOFTWARE.
  #
  # For more information, please refer to <http://unlicense.org/>

